require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.2
Style/Documentation:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
